import ReduxProvider from '../redux/ReduxProvider';
import { Inter } from 'next/font/google';
import { AuthProvider } from '../provider/AuthContext';
import Menu from '@/layouts/Menu';
import '../assets/css/mystyle.css';
import '../assets/css/animate.min.css';
import '../assets/css/bootstrap.min.css';
import '../assets/css/default.css';
import '../assets/css/fontawesome-all.min.css';
import '../assets/css/magnific-popup.css';
import '../assets/css/responsive.css';
import '../assets/css/slick.css';
import '../assets/css/style.css';
import '../assets/css/swiper-bundle.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <ReduxProvider>
            <Menu />
            {children}
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
